[workspace]
members = [
    "nix-c-raw",
    "nix-expr",
    "nix-fetchers",
    "nix-flake",
    "nix-store",
    "nix-util",
    "nixops4-core",
    "nixops4-eval",
    "nixops4-resource",
    "nixops4-resource-runner",
    "nixops4-resources-local",
    "nixops4",
]
resolver = "2"
